jenkins:
  systemMessage: "Jenkins - Shopping Website CI/CD"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - script: |
      pipelineJob('jenkins-sample') {
        description('Shopping Website CI/CD Pipeline')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/pro5251/jenkins-sample.git')
                }
                branch('*/main')
              }
            }
            scriptPath('jenkins/Jenkinsfile')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
      }
